### ISSUE TITLE
win-1.5.4-202205201318版本串口端口加载不出来（无法设置）

### ISSUE THREAD

**Issue by wenpo1975** [nxshell/nxshell#172]
![image](https://user-images.githubusercontent.com/24839804/170804966-0f1ca68e-1a28-4e9d-8503-513066b27a76.png)

如图，旧版的这个位置，win-1.5.4-202205201318点不出来，无显示端口。

**Comment by nxshell** [comment]
1.5.3版本可以？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年05月28日 09:46 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [nxshell/nxshell] win-1.5.4-202205201318版本串口端口加载不出来（无法设置） (Issue #172) |

如图，旧版的这个位置，win-1.5.4-202205201318点不出来，无显示端口。

**Comment by wenpo1975** [comment]
> 1.5.3版本可以？
> [...](#)
> ---- 回复的原邮件 ---- |发件人 |@***.***> | |日期 |2022年05月28日 09:46 | |收件人 |@***.***> | |抄送至 |@***.***> | |主题 |[nxshell/nxshell] win-1.5.4-202205201318版本串口端口加载不出来（无法设置） （问题 #172） |如图，旧版的这个位置，win-1.5.4-202205201318点不出来，无显示端口。— 直接回复此电子邮件、在 GitHub 上查看或取消订阅。您收到此消息是因为您订阅了此线程。消息 ID： ***@***.***>

1.5.3我没试，我直接退到1.5.0是可以的，我一会试试1.5.3看看。

**Comment by waitsaber** [comment]
今天我win11也遇到了这个问题，在1.5.3是可以正常识别使用的
![image](https://user-images.githubusercontent.com/67093172/170835718-86240a90-8c55-4827-a011-4779b0c50aed.png)

**Comment by nxshell** [comment]
在命令行启动nxshell 看看打开串口设置报啥错误



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年05月29日 01:16 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [nxshell/nxshell] win-1.5.4-202205201318版本串口端口加载不出来（无法设置） (Issue #172) |

今天我win11也遇到了这个问题，在1.5.3是可以正常识别使用的

**Comment by waitsaber** [comment]
1.5.4使用命令行运行提示的错误是“serialport import failed  Error: Cannot find module 'serialport'”，具体的可以查看下面的记录

`PS D:\Program Files\NxShell> .\NxShell.exe
PS D:\Program Files\NxShell>
serialport import failed  Error: Cannot find module 'serialport'
Require stack:
- D:\Program Files\NxShell\resources\apps\powertools-shell\index.js
- D:\Program Files\NxShell\resources\app.asar\AppLoader.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (D:\Program Files\NxShell\resources\apps\powertools-shell\index.js:61:296380)
    at r (D:\Program Files\NxShell\resources\apps\powertools-shell\index.js:1:158)
    at Object.<anonymous> (D:\Program Files\NxShell\resources\apps\powertools-shell\index.js:61:807)
    at r (D:\Program Files\NxShell\resources\apps\powertools-shell\index.js:1:158)
    at Object.<anonymous> (D:\Program Files\NxShell\resources\apps\powertools-shell\index.js:1:260616) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\Program Files\\NxShell\\resources\\apps\\powertools-shell\\index.js',
    'D:\\Program Files\\NxShell\\resources\\app.asar\\AppLoader.js'
  ]
}
node pty load failed Error: Cannot find module 'node-pty'
Require stack:
- D:\Program Files\NxShell\resources\apps\powertools-shell\index.js
- D:\Program Files\NxShell\resources\app.asar\AppLoader.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (D:\Program Files\NxShell\resources\apps\powertools-shell\index.js:61:400446)
    at r (D:\Program Files\NxShell\resources\apps\powertools-shell\index.js:1:158)
    at Object.<anonymous> (D:\Program Files\NxShell\resources\apps\powertools-shell\index.js:61:393432)
    at r (D:\Program Files\NxShell\resources\apps\powertools-shell\index.js:1:158)
    at Object.<anonymous> (D:\Program Files\NxShell\resources\apps\powertools-shell\index.js:1:260630)
    at r (D:\Program Files\NxShell\resources\apps\powertools-shell\index.js:1:158)
    at Object.<anonymous> (D:\Program Files\NxShell\resources\apps\powertools-shell\index.js:61:45016)
    at r (D:\Program Files\NxShell\resources\apps\powertools-shell\index.js:1:158)
    at D:\Program Files\NxShell\resources\apps\powertools-shell\index.js:1:957
    at Object.<anonymous> (D:\Program Files\NxShell\resources\apps\powertools-shell\index.js:1:968)
    at Module._compile (internal/modules/cjs/loader.js:1078:30) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\Program Files\\NxShell\\resources\\apps\\powertools-shell\\index.js',
    'D:\\Program Files\\NxShell\\resources\\app.asar\\AppLoader.js'
  ]
}
(node:13196) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `NxShell --trace-deprecation ...` to show where the warning was created)
unix sock listen on  \\?\pipe\13196.sock
get serial prots error  TypeError: Cannot read property 'list' of null
    at D:\Program Files\NxShell\resources\apps\powertools-shell\index.js:61:7892
    at f (D:\Program Files\NxShell\resources\apps\powertools-shell\index.js:1:19785)
    at Generator._invoke (D:\Program Files\NxShell\resources\apps\powertools-shell\index.js:1:19538)
    at Generator.next (D:\Program Files\NxShell\resources\apps\powertools-shell\index.js:1:20148)
    at n (D:\Program Files\NxShell\resources\apps\powertools-shell\index.js:1:26489)
    at s (D:\Program Files\NxShell\resources\apps\powertools-shell\index.js:1:26705)
    at D:\Program Files\NxShell\resources\apps\powertools-shell\index.js:1:26764
    at new Promise (<anonymous>)
    at Object.<anonymous> (D:\Program Files\NxShell\resources\apps\powertools-shell\index.js:1:26645)
    at Object.B (D:\Program Files\NxShell\resources\apps\powertools-shell\index.js:61:8145)
    at Object.getSerialPorts (D:\Program Files\NxShell\resources\apps\powertools-shell\index.js:61:8231)
    at RPCServer.dispatchCall (D:\Program Files\NxShell\resources\app.asar\AppLoader.js:1:2339)
    at D:\Program Files\NxShell\resources\app.asar\AppLoader.js:1:6386
    at dispatch (D:\Program Files\NxShell\resources\app.asar\AppLoader.js:1:3006)
    at process.<anonymous> (D:\Program Files\NxShell\resources\app.asar\AppLoader.js:1:6334)
    at process.emit (events.js:315:20)`

**Comment by nxshell** [comment]
好的 收到！



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年05月29日 21:31 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [nxshell/nxshell] win-1.5.4-202205201318版本串口端口加载不出来（无法设置） (Issue #172) |

1.5.4使用命令行运行提示的错误是“serialport import failed Error: Cannot find module 'serialport'”，具体的可以查看下面的记录

`PS D:\Program Files\NxShell> .\NxShell.exe
PS D:\Program Files\NxShell>
serialport import failed Error: Cannot find module 'serialport'
Require stack:

D:\Program Files\NxShell\resources\apps\powertools-shell\index.js
D:\Program Files\NxShell\resources\app.asar\AppLoader.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
at Module._load (internal/modules/cjs/loader.js:732:27)
at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
at Module.require (internal/modules/cjs/loader.js:959:19)
at require (internal/modules/cjs/helpers.js:88:18)
at Object. (D:\Program Files\NxShell\resources\apps\powertools-shell\index.js:61:296380)
at r (D:\Program Files\NxShell\resources\apps\powertools-shell\index.js:1:158)
at Object. (D:\Program Files\NxShell\resources\apps\powertools-shell\index.js:61:807)
at r (D:\Program Files\NxShell\resources\apps\powertools-shell\index.js:1:158)
at Object. (D:\Program Files\NxShell\resources\apps\powertools-shell\index.js:1:260616) {
code: 'MODULE_NOT_FOUND',
requireStack: [
'D:\Program Files\NxShell\resources\apps\powertools-shell\index.js',
'D:\Program Files\NxShell\resources\app.asar\AppLoader.js'
]
}
node pty load failed Error: Cannot find module 'node-pty'
Require stack:
D:\Program Files\NxShell\resources\apps\powertools-shell\index.js
D:\Program Files\NxShell\resources\app.asar\AppLoader.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
at Module._load (internal/modules/cjs/loader.js:732:27)
at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
at Module.require (internal/modules/cjs/loader.js:959:19)
at require (internal/modules/cjs/helpers.js:88:18)
at Object. (D:\Program Files\NxShell\resources\apps\powertools-shell\index.js:61:400446)
at r (D:\Program Files\NxShell\resources\apps\powertools-shell\index.js:1:158)
at Object. (D:\Program Files\NxShell\resources\apps\powertools-shell\index.js:61:393432)
at r (D:\Program Files\NxShell\resources\apps\powertools-shell\index.js:1:158)
at Object. (D:\Program Files\NxShell\resources\apps\powertools-shell\index.js:1:260630)
at r (D:\Program Files\NxShell\resources\apps\powertools-shell\index.js:1:158)
at Object. (D:\Program Files\NxShell\resources\apps\powertools-shell\index.js:61:45016)
at r (D:\Program Files\NxShell\resources\apps\powertools-shell\index.js:1:158)
at D:\Program Files\NxShell\resources\apps\powertools-shell\index.js:1:957
at Object. (D:\Program Files\NxShell\resources\apps\powertools-shell\index.js:1:968)
at Module._compile (internal/modules/cjs/loader.js:1078:30) {
code: 'MODULE_NOT_FOUND',
requireStack: [
'D:\Program Files\NxShell\resources\apps\powertools-shell\index.js',
'D:\Program Files\NxShell\resources\app.asar\AppLoader.js'
]
}
(node:13196) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use NxShell --trace-deprecation ... to show where the warning was created)
unix sock listen on \?\pipe\13196.sock
get serial prots error TypeError: Cannot read property 'list' of null
at D:\Program Files\NxShell\resources\apps\powertools-shell\index.js:61:7892
at f (D:\Program Files\NxShell\resources\apps\powertools-shell\index.js:1:19785)
at Generator._invoke (D:\Program Files\NxShell\resources\apps\powertools-shell\index.js:1:19538)
at Generator.next (D:\Program Files\NxShell\resources\apps\powertools-shell\index.js:1:20148)
at n (D:\Program Files\NxShell\resources\apps\powertools-shell\index.js:1:26489)
at s (D:\Program Files\NxShell\resources\apps\powertools-shell\index.js:1:26705)
at D:\Program Files\NxShell\resources\apps\powertools-shell\index.js:1:26764
at new Promise ()
at Object. (D:\Program Files\NxShell\resources\apps\powertools-shell\index.js:1:26645)
at Object.B (D:\Program Files\NxShell\resources\apps\powertools-shell\index.js:61:8145)
at Object.getSerialPorts (D:\Program Files\NxShell\resources\apps\powertools-shell\index.js:61:8231)
at RPCServer.dispatchCall (D:\Program Files\NxShell\resources\app.asar\AppLoader.js:1:2339)
at D:\Program Files\NxShell\resources\app.asar\AppLoader.js:1:6386
at dispatch (D:\Program Files\NxShell\resources\app.asar\AppLoader.js:1:3006)
at process. (D:\Program Files\NxShell\resources\app.asar\AppLoader.js:1:6334)
at process.emit (events.js:315:20)`

**Comment by nxshell** [comment]
Fixed v1.6.0
