### ISSUE TITLE
MANJARO 无法打开nxshell

### ISSUE THREAD

**Issue by wistarine** [nxshell/nxshell#83]
system version:Linux  5.13.15-1-MANJARO
installed from snap, cannot open, just white windows like this:
<img width="1280" alt="w" src="https://user-images.githubusercontent.com/34701597/133868942-759cd4a2-ea4b-4c4e-bd51-1883ea944634.png">

**Comment by nxshell** [comment]
@wistarine  能提供一下snap报错信息吗？

**Comment by JaimeZeng** [comment]
> @wistarine 能提供一下snap报错信息吗？

```bash
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
Gtk-Message: 18:48:55.328: Failed to load module "xapp-gtk3-module"
Gtk-Message: 18:48:55.354: Failed to load module "colorreload-gtk-module"
Gtk-Message: 18:48:55.354: Failed to load module "window-decorations-gtk-module"
(node:72287) UnhandledPromiseRejectionWarning: Error: spawn EPERM
    at ChildProcess.spawn (internal/child_process.js:407:11)
    at spawn (child_process.js:557:9)
    at fork (child_process.js:125:10)
    at new a (/snap/nxshell/13/resources/app.asar/index.js:1:70837)
    at e.exports.AppServiceManager.createService (/snap/nxshell/13/resources/app.asar/index.js:1:71792)
    at m._createService (/snap/nxshell/13/resources/app.asar/index.js:1:66504)
    at /snap/nxshell/13/resources/app.asar/index.js:1:65016
(node:72287) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:72287) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by nxshell** [comment]
@JaimeZeng  sudo 试一试？

**Comment by JaimeZeng** [comment]
@nxshell sudo 下还是不行...

```bash
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
/snap/nxshell/13/resources/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /snap/nxshell/13/resources/node_modules/@serialport/bindings/build/Release/bindings.node)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1196:18)
    at Object.func [as .node] (electron/js2c/asar.js:140:31)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Module._load (internal/modules/cjs/loader.js:881:14)
    at Function.Module._load (electron/js2c/asar.js:779:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at bindings (/snap/nxshell/13/resources/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/snap/nxshell/13/resources/node_modules/@serialport/bindings/lib/linux.js:2:36)
close: 1 null

```

**Comment by nxshell** [comment]
@JaimeZeng  你的系统glibc是版本多少？

**Comment by JaimeZeng** [comment]
@nxshell 2.33的

`ldd (GNU libc) 2.33`

**Comment by nxshell** [comment]
@wistarine @JaimeZeng  重新下载snap包测试下。已经fix啦

**Comment by JaimeZeng** [comment]
@nxshell 打开后还是一片空白。

[error.log](https://github.com/nxshell/nxshell/files/7231248/error.log)

**Comment by JaimeZeng** [comment]
> @nxshell 打开后还是一片空白，报错内容 [error.log](https://github.com/nxshell/nxshell/files/7231248/error.log)

sudo 下可以打开了

**Comment by nxshell** [comment]
release 1.4.5
